version: "3.2"
services:

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${WEB_ROOT}/:/var/www/html/
    depends_on:
      - redis

  mysql:
    container_name: db
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT:-}"
      MYSQL_DATABASE: "${DB_NAME:-default_database}"
      MYSQL_USER: "${DB_USER:-admin}"
      MYSQL_PASSWORD: "${DB_PASS:-Admin123!@#}"

  redis:
    container_name: cache
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    depends_on:
      - mysql
    command: redis-server --appendonly yes

volumes:
  database:
  cache:
