UBUNTU_IMAGE ||= "hashicorp/precise64"
CENTOS_IMAGE ||= "centos/7"

Vagrant.configure("2") do |config|
  # Create slave nodes
  config.vm.define "node1" do |node|
    node.vm.box = UBUNTU_IMAGE
    node.vm.box_check_update = false
    node.vm.network :private_network, ip: "192.168.33.44"
    node.vm.hostname = "node1"
    node.vm.provider :virtualbox do |vb|
      vb.name = "node1"
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected", "--memory", 1024, "--cpus", "1", "--hwvirtex", "on"]
    end
  end

  config.vm.define "node2" do |node|
    node.vm.box = CENTOS_IMAGE
    node.vm.box_check_update = false
    node.vm.network :private_network, ip: "192.168.33.45"
    node.vm.hostname = "node2"
    node.vm.provider :virtualbox do |vb|
      vb.name = "node2"
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected", "--memory", 1024, "--cpus", "1", "--hwvirtex", "on"]
	end
  end

  # Create master node
  config.vm.define "master", primary: true do |master|
    master.vm.box = CENTOS_IMAGE
    master.vm.box_check_update = false
    master.vm.network :private_network, ip: "192.168.33.10"
    master.vm.network :forwarded_port, guest: 80, host: 8080
    master.vm.hostname = "master"
    master.vm.provider :virtualbox do |vb|
      vb.name = "master"
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected", "--memory", 1024, "--cpus", "1", "--hwvirtex", "on", "--natdnshostresolver1", "on"]
    end

    # Run ansible playbook
    master.vm.provision :ansible do |ansible|
      ansible.limit = "all"
      ansible.playbook = "playbook.yml"
    end
  end
end
